version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker
    volumes:
      # - ./proxy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/nginx/proxy-tmpl/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - "${HOST_STATIC_ROOT}:${NGINX_STATIC_ROOT}:ro"
    ports:
      - "80:80"
    command: >
      /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
      < /etc/nginx/templates/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    depends_on:
      - portal

  portal:
    build:
      context: .
    restart: unless-stopped
    container_name: portal
    env_file:
      - .env
      - .env.docker
    ports:
      - "${CORE_API_PORT}:${CORE_API_PORT}"
    depends_on:
      - migrate

  postgres:
    build:
      context: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  migrate:
    build:
      context: migrations
    restart: on-failure
    env_file:
      - .env
      - .env.docker

volumes:
  static-files:
