version: "3.8"

# Start theses services for local development

services:
  postgres:
    build:
      context: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  migrate:
    build:
      context: migrations
    container_name: migrate
    restart: on-failure
    env_file:
      - .env
      - .env.docker
    depends_on:
      - postgres
