version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - "${HOST_CMSAPI_FILES_DIR}:${NGINX_CMSAPI_FILES_DIR}:ro"
    ports:
      - "80:80"
    command: >
      /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
      < /etc/nginx/templates/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    depends_on:
      - web-client
      - web-api
      - cms

  web-client:
    image: ghcr.io/reframework/shopana-web-client:${WEBAPP_VERSION:-latest}
    restart: unless-stopped

  web-api:
    image: ghcr.io/reframework/shopana-web-api:${WEBAPP_VERSION:-latest}
    restart: unless-stopped
    depends_on:
      - web-migration
      - postgres

  web-migration:
    image: ghcr.io/reframework/shopana-web-migration:latest
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres

  cms:
    image: ghcr.io/reframework/shopana-cms:${PORTAL_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${HOST_CMSAPI_FILES_DIR}:${CMSAPI_FILES_DIR}"
    depends_on:
      - cms-migration
      - postgres

  cms-migration:
    image: ghcr.io/reframework/shopana-cms-migration:latest
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: ghcr.io/reframework/shopana-postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${HOST_DB_DATA}:/var/lib/postgresql/data"
