version: "3.8"

services:
  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres

  migrate:
    extends:
      file: docker-compose.common.yml
      service: migrate

  api:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - migrate
