package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	graph_gen "webapi/internal/http/graphql/generated"
)

// Mutation returns graph_gen.MutationResolver implementation.
func (r *Resolver) Mutation() graph_gen.MutationResolver { return &mutationResolver{r} }

// Query returns graph_gen.QueryResolver implementation.
func (r *Resolver) Query() graph_gen.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
