version: "3.8"

services:
  api:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  postgres:
    build:
      context: postgres
    container_name: shopana-platform-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432

  migrations:
    build:
      context: migrations
    container_name: shopana-platgorm-migrations
    restart: on-failure
    env_file:
      - .env
