version: "3.8"

services:
  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres

  migrations:
    extends:
      file: docker-compose.common.yml
      service: migrations
    depends_on:
      - postgres

  webapi:
    extends:
      file: docker-compose.common.yml
      service: webapi
    depends_on:
      - postgres
      - migrate
