name: Build and Publish Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  changes:
    name: Checking
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      api: ${{ steps.filter.outputs.api }}
      migrations: ${{ steps.filter.outputs.migrations }}
      postgres: ${{ steps.filter.outputs.postgres }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ github.token }}
          filters: |
            api:
              - 'api/internal/**'
            migrations:
              - 'api/migrations/**'
            postgres:
              - 'api/postgres/**'
            client:
              - 'client/**'

  publish-api:
    name: Publish / API
    needs: changes
    if: needs.changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/reframework/shopana-web-api:latest

  publish-client:
    name: Publish / Client
    needs: changes
    if: needs.changes.outputs.client == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/reframework/shopana-web-client:latest
          build-args: |
            NEXT_PUBLIC_WEBAPP_GA_TOKEN=${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID }}
            NEXT_PUBLIC_WEBAPP_ROLLBAR_CLIENT_TOKEN=${{ vars.NEXT_PUBLIC_ROLLBAR_CLIENT_TOKEN }}

  publish-migration:
    name: Publish / Migration
    needs: changes
    if: needs.changes.outputs.migrations == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./api/migrations
          push: true
          tags: |
            ghcr.io/reframework/shopana-platform-migration:latest

  publish-postgres:
    name: Publish / Postgres
    needs: changes
    if: needs.changes.outputs.postgres == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./api/postgres
          push: true
          tags: |
            ghcr.io/reframework/shopana-platform-postgres:latest
